/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BroadcastServerJFrame.java
 * 
 */

package it.unibo.deis.lia.ramp.service.application;

//import it.unibo.deis.lia.ramp.core.e2e.E2EComm;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;


/**
 *
 * @author useruser
 */
public class BroadcastServiceJFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String[] sourceList;
    private String[] programList;

    private BroadcastService bs;
    /** Creates new form FileSharingServerJFrame */
    public BroadcastServiceJFrame(BroadcastService bs) {
        this.bs=bs;
        initComponents();

        jTextFieldCurrentDirectory.setText(bs.getRepositoryDirectory());
        jButtonRefreshSourceListActionPerformed(null);
        jButtonRefreshProgramListActionPerformed(null);
        jTextFieldWebcamName.setText(bs.getWebcam());
        jTextFieldVlcDirectory.setText(bs.getVlcDirectory());
        jButtonRefreshActionPerformed(null);
        jCheckBoxBroadcastSplitterActionPerformed(null);
        jCheckBoxRawBytesActionPerformed(null);
        jRadioButtonTranscodeActionPerformed(null);
        //jRadioButtonProtocolActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTranscode = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonChangeVlcDirectory = new javax.swing.JButton();
        jButtonChangeWebcam = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldWebcamName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldVlcDirectory = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCurrentDirectory = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNewDirectory = new javax.swing.JTextField();
        jButtonChangeDirectory = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonActivateDvbT = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFrequency = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldProgram = new javax.swing.JTextField();
        jButtonActivateHttp = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonRefreshSourceList = new javax.swing.JButton();
        jButtonRefreshProgramList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSourceList = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaActiveProgramList = new javax.swing.JTextArea();
        jComboBoxSourceList = new javax.swing.JComboBox();
        jComboBoxActiveProgramList = new javax.swing.JComboBox();
        jButtonActivateProgram = new javax.swing.JButton();
        jButtonStopProgram = new javax.swing.JButton();
        jButtonConfigProgram = new javax.swing.JButton();
        jCheckBoxBroadcastSplitter = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jButtonSet = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldVideoBitrate = new javax.swing.JTextField();
        jTextFieldAudioBitrate = new javax.swing.JTextField();
        jTextFieldVideoScale = new javax.swing.JTextField();
        jTextFieldGopSize = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMtu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButtonNoTranscode = new javax.swing.JRadioButton();
        jRadioButtonMp2v = new javax.swing.JRadioButton();
        jRadioButtonMp2v.setSelected(true);
        jRadioButtonH264 = new javax.swing.JRadioButton();
        jCheckBoxRawBytes = new javax.swing.JCheckBox();
        jCheckBoxSmartSplitter = new javax.swing.JCheckBox();
        rdbtnAndr = new JRadioButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BroadcastService");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonChangeVlcDirectory.setText("change vlc directory");
        jButtonChangeVlcDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeVlcDirectoryActionPerformed(evt);
            }
        });

        jButtonChangeWebcam.setText("change webcam");
        jButtonChangeWebcam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeWebcamActionPerformed(evt);
            }
        });

        jLabel4.setText("webcam name");

        jLabel5.setText("vlc directory");

        jLabel1.setText("current repository directory");

        jTextFieldCurrentDirectory.setEditable(false);

        jLabel2.setText("new repository directory");

        jButtonChangeDirectory.setText("change directory");
        jButtonChangeDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_jPanel1 = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(gl_jPanel1);
        gl_jPanel1.setHorizontalGroup(
            gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_jPanel1.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_jPanel1.createSequentialGroup()
                        .addComponent(jButtonChangeWebcam, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldWebcamName, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                    .addGroup(gl_jPanel1.createSequentialGroup()
                        .addComponent(jButtonChangeVlcDirectory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVlcDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
                    .addGroup(gl_jPanel1.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCurrentDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE))
                    .addGroup(gl_jPanel1.createSequentialGroup()
                        .addComponent(jButtonChangeDirectory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNewDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gl_jPanel1.setVerticalGroup(
            gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_jPanel1.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChangeWebcam)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldWebcamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChangeVlcDirectory)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldVlcDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCurrentDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gl_jPanel1.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNewDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeDirectory)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jButtonActivateDvbT.setText("activate dvb-t");
        jButtonActivateDvbT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateDvbTActionPerformed(evt);
            }
        });

        jLabel3.setText("frequency (kHz)");

        jTextFieldFrequency.setText("842000");

        jLabel6.setText("program");

        jTextFieldProgram.setText("1");

        jButtonActivateHttp.setText("activate http");
        jButtonActivateHttp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateHttpActionPerformed(evt);
            }
        });

        jLabel7.setText("http://");

        jTextFieldHost.setText("wbgo.streamguys.net:8000");
        jTextFieldHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_jPanel2 = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(gl_jPanel2);
        gl_jPanel2.setHorizontalGroup(
            gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_jPanel2.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonActivateHttp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonActivateDvbT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_jPanel2.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gl_jPanel2.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        gl_jPanel2.setVerticalGroup(
            gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_jPanel2.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActivateDvbT)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_jPanel2.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActivateHttp)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonRefreshSourceList.setText("refresh source list");
        jButtonRefreshSourceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshSourceListActionPerformed(evt);
            }
        });

        jButtonRefreshProgramList.setText("refresh active program list");
        jButtonRefreshProgramList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshProgramListActionPerformed(evt);
            }
        });

        jTextAreaSourceList.setColumns(20);
        jTextAreaSourceList.setEditable(false);
        jTextAreaSourceList.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSourceList);

        jTextAreaActiveProgramList.setColumns(20);
        jTextAreaActiveProgramList.setRows(5);
        jScrollPane2.setViewportView(jTextAreaActiveProgramList);

        jComboBoxSourceList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSourceList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSourceListActionPerformed(evt);
            }
        });

        jComboBoxActiveProgramList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonActivateProgram.setText("activate program");
        jButtonActivateProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivateProgramActionPerformed(evt);
            }
        });

        jButtonStopProgram.setText("stop program");
        jButtonStopProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStopProgramActionPerformed(evt);
            }
        });

        jButtonConfigProgram.setText("get program config");
        jButtonConfigProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_jPanel3 = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(gl_jPanel3);
        gl_jPanel3.setHorizontalGroup(
            gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_jPanel3.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_jPanel3.createSequentialGroup()
                        .addComponent(jButtonRefreshSourceList, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefreshProgramList, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
                    .addGroup(gl_jPanel3.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                    .addGroup(gl_jPanel3.createSequentialGroup()
                        .addGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonActivateProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                            .addComponent(jComboBoxSourceList, javax.swing.GroupLayout.Alignment.LEADING, 0, 480, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxActiveProgramList, 0, 482, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_jPanel3.createSequentialGroup()
                                .addComponent(jButtonConfigProgram, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonStopProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        gl_jPanel3.setVerticalGroup(
            gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_jPanel3.createSequentialGroup()
                .addContainerGap()
                .addGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefreshSourceList)
                    .addComponent(jButtonRefreshProgramList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSourceList, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxActiveProgramList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gl_jPanel3.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActivateProgram)
                    .addComponent(jButtonStopProgram)
                    .addComponent(jButtonConfigProgram))
                .addContainerGap())
        );

        jCheckBoxBroadcastSplitter.setSelected(true);
        jCheckBoxBroadcastSplitter.setText("BroadcastSplitter");
        jCheckBoxBroadcastSplitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBroadcastSplitterActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Stream Parameters"));

        jButtonSet.setText("set");
        jButtonSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSetActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jLabel8.setText("video bitrate (kbit/s)");

        jLabel9.setText("audio bitrate (kbit/s)");

        jLabel10.setText("GoP size");

        jLabel11.setText("video scale");

        jTextFieldAudioBitrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAudioBitrateActionPerformed(evt);
            }
        });

        jTextFieldVideoScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVideoScaleActionPerformed(evt);
            }
        });

        jLabel12.setText("MTU (bytes)");

        buttonGroupTranscode.add(jRadioButtonNoTranscode);
        jRadioButtonNoTranscode.setText("no transcode");
        jRadioButtonNoTranscode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTranscodeActionPerformed(evt);
            }
        });

        buttonGroupTranscode.add(jRadioButtonMp2v);
        jRadioButtonMp2v.setText("mp2v");
        jRadioButtonMp2v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jRadioButtonMp2vActionPerformed(evt);
            	jRadioButtonTranscodeActionPerformed(evt);
            }
        });

        buttonGroupTranscode.add(jRadioButtonH264);
        jRadioButtonH264.setText("x264");
        jRadioButtonH264.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //jRadioButtonH264ActionPerformed(evt);
            	jRadioButtonTranscodeActionPerformed(evt);
            }
        });
        
        buttonGroupTranscode.add(rdbtnAndr);
        rdbtnAndr.setText("Andr");
        rdbtnAndr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jRadioButtonTranscodeActionPerformed(evt);
            }
        });

        jCheckBoxRawBytes.setText("raw bytes");
        jCheckBoxRawBytes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxRawBytesActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout gl_jPanel4 = new javax.swing.GroupLayout(jPanel4);
        gl_jPanel4.setHorizontalGroup(
        	gl_jPanel4.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel4.createSequentialGroup()
        			.addGroup(gl_jPanel4.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_jPanel4.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(gl_jPanel4.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_jPanel4.createSequentialGroup()
        							.addComponent(jButtonSet)
        							.addGap(18)
        							.addComponent(jLabel12)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jTextFieldMtu, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_jPanel4.createSequentialGroup()
        							.addGroup(gl_jPanel4.createParallelGroup(Alignment.LEADING, false)
        								.addGroup(gl_jPanel4.createSequentialGroup()
        									.addComponent(jLabel9)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jTextFieldAudioBitrate))
        								.addGroup(gl_jPanel4.createSequentialGroup()
        									.addComponent(jLabel8)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jTextFieldVideoBitrate, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)))
        							.addGap(18)
        							.addGroup(gl_jPanel4.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel10)
        								.addComponent(jLabel11))))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(gl_jPanel4.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jTextFieldGopSize, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        						.addComponent(jTextFieldVideoScale, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        						.addComponent(jButtonRefresh)))
        				.addGroup(gl_jPanel4.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jRadioButtonNoTranscode)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jRadioButtonMp2v)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jRadioButtonH264)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(rdbtnAndr, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jCheckBoxRawBytes))
        				.addComponent(jSeparator1, GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        			.addGap(10))
        );
        gl_jPanel4.setVerticalGroup(
        	gl_jPanel4.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_jPanel4.createSequentialGroup()
        			.addGroup(gl_jPanel4.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(jTextFieldVideoBitrate, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel11)
        				.addComponent(jTextFieldVideoScale, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_jPanel4.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextFieldAudioBitrate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel9)
        				.addComponent(jLabel10)
        				.addComponent(jTextFieldGopSize, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_jPanel4.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonSet)
        				.addComponent(jLabel12)
        				.addComponent(jTextFieldMtu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButtonRefresh))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(gl_jPanel4.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jRadioButtonNoTranscode)
        				.addComponent(jRadioButtonMp2v)
        				.addComponent(jRadioButtonH264)
        				.addComponent(rdbtnAndr)
        				.addComponent(jCheckBoxRawBytes)))
        );
        jPanel4.setLayout(gl_jPanel4);

        jCheckBoxSmartSplitter.setText("smart splitter");
        jCheckBoxSmartSplitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSmartSplitterActionPerformed(evt);
            }
        });
        
        /*rdbtnUdp = new JRadioButton("UDP");
        rdbtnUdp.setSelected(true);
        rdbtnUdp.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		jRadioButtonProtocolActionPerformed(evt);
        	}
        });
        buttonGroupProtocol.add(rdbtnUdp);
        
        rdbtnTcp = new JRadioButton("TCP");
        rdbtnTcp.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		jRadioButtonProtocolActionPerformed(evt);
        	}
        });
        buttonGroupProtocol.add(rdbtnTcp);*/

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(10)
        							.addComponent(jCheckBoxBroadcastSplitter)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jCheckBoxSmartSplitter)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 416, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jCheckBoxBroadcastSplitter)
        						.addComponent(jCheckBoxSmartSplitter)))
        				.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGap(18)
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChangeDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeDirectoryActionPerformed
        String newDirectory=jTextFieldNewDirectory.getText();
        if(new java.io.File(newDirectory).isDirectory()){
            bs.setRepositoryDirectory(newDirectory);

            jTextFieldCurrentDirectory.setText(bs.getRepositoryDirectory());
            jButtonRefreshSourceListActionPerformed(null);
        }
        else{
            System.out.println("BroadcastServiceJFrame: invalid new dirctory "+newDirectory);
        }
    }//GEN-LAST:event_jButtonChangeDirectoryActionPerformed

    private void jButtonRefreshProgramListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshProgramListActionPerformed
        //System.out.println("BroadcastService: jButtonRefreshProgramListActionPerformed");
        programList = bs.getProgramList();
        String text="";
        String[] items=new String[programList.length];
        for (int i=0; i<programList.length; i++){
            text+=programList[i]+"\n";
            items[i]=""+programList[i];
        }
        this.jTextAreaActiveProgramList.setText(text);
        DefaultComboBoxModel dcm = new DefaultComboBoxModel(items);
        this.jComboBoxActiveProgramList.setModel(dcm);
    }//GEN-LAST:event_jButtonRefreshProgramListActionPerformed

    private void jButtonChangeWebcamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeWebcamActionPerformed
        bs.setWebcam(jTextFieldWebcamName.getText());
        try {
            Thread.sleep(10);
        } catch (InterruptedException ex) {
            //
        }
        this.jButtonRefreshSourceListActionPerformed(null);
    }//GEN-LAST:event_jButtonChangeWebcamActionPerformed

    private void jButtonChangeVlcDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeVlcDirectoryActionPerformed
        bs.setVlcDirectory(jTextFieldVlcDirectory.getText());
    }//GEN-LAST:event_jButtonChangeVlcDirectoryActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //System.out.println("BroadcastService: formWindowClosing");
        bs.stopService();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonRefreshSourceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshSourceListActionPerformed
        //System.out.println("BroadcastService: jButtonRefreshSourceListActionPerformed");
        sourceList = bs.getSourceList();
        String text="";
        String[] items=new String[sourceList.length];
        for (int i=0; i<sourceList.length; i++){
            text+=sourceList[i]+"\n";
            items[i]=""+sourceList[i];
        }
        jTextAreaSourceList.setText(text);
        DefaultComboBoxModel dcm = new DefaultComboBoxModel(items);
        this.jComboBoxSourceList.setModel(dcm);
    }//GEN-LAST:event_jButtonRefreshSourceListActionPerformed

    private void jButtonActivateProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateProgramActionPerformed
        //System.out.println("BroadcastService: jButtonActivateProgramActionPerformed");
        try{
            int index = jComboBoxSourceList.getSelectedIndex();
            if(index!=-1){

                final String selectedSource = sourceList[index];
                Thread t = new Thread(
                        new Runnable(){
                            @Override
                            public void run() {
                                try {
                                    bs.addProgram(selectedSource);
                                } catch (Exception ex) {
                                    ex.printStackTrace();
                                }
                            }
                        }
                );
                t.start();
            }
            Thread.sleep(100);
        }
        catch(Exception e){
            e.printStackTrace();
        }
        jButtonRefreshProgramListActionPerformed(null);
    }//GEN-LAST:event_jButtonActivateProgramActionPerformed

    private void jButtonStopProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStopProgramActionPerformed
        int index = jComboBoxActiveProgramList.getSelectedIndex();
        if(index!=-1){
            bs.removeProgram(programList[index]);
        }
        /*try {
            Thread.sleep(250);
        } catch (InterruptedException ex) {
           ex.printStackTrace();
        }*/
        jButtonRefreshProgramListActionPerformed(null);
    }//GEN-LAST:event_jButtonStopProgramActionPerformed

    private void jButtonActivateDvbTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateDvbTActionPerformed
        String program = "dvb-t "+jTextFieldFrequency.getText()+" "+jTextFieldProgram.getText();
        try {
            bs.addProgram(program);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        this.jButtonRefreshProgramListActionPerformed(null);
    }//GEN-LAST:event_jButtonActivateDvbTActionPerformed

    private void jCheckBoxBroadcastSplitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBroadcastSplitterActionPerformed
        boolean selected = this.jCheckBoxBroadcastSplitter.getModel().isSelected();
        if(selected){
            bs.startBroadcastSplitter();
            this.jCheckBoxSmartSplitterActionPerformed(null);
            this.jCheckBoxSmartSplitter.setEnabled(true);
        }
        else{
            this.jCheckBoxSmartSplitter.setEnabled(false);
            bs.stopBroadcastSplitter();
        }
    }//GEN-LAST:event_jCheckBoxBroadcastSplitterActionPerformed

    private void jButtonActivateHttpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivateHttpActionPerformed
        String program = "http "+jTextFieldHost.getText();//+" "+jTextFieldPort.getText();
        try {
            bs.addProgram(program);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        this.jButtonRefreshProgramListActionPerformed(null);
    }//GEN-LAST:event_jButtonActivateHttpActionPerformed

    private void jComboBoxSourceListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSourceListActionPerformed
        // do nothing
    }//GEN-LAST:event_jComboBoxSourceListActionPerformed

    private void jTextFieldHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHostActionPerformed
        // do nothing
    }//GEN-LAST:event_jTextFieldHostActionPerformed

    private void jTextFieldAudioBitrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAudioBitrateActionPerformed
        // do nothing
    }//GEN-LAST:event_jTextFieldAudioBitrateActionPerformed

    private void jTextFieldVideoScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVideoScaleActionPerformed
        // do nothing
    }//GEN-LAST:event_jTextFieldVideoScaleActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        this.jTextFieldVideoBitrate.setText(""+bs.getVideoBitrate());
        this.jTextFieldVideoScale.setText(""+bs.getVideoScale());
        this.jTextFieldAudioBitrate.setText(""+bs.getAudioBirate());
        this.jTextFieldGopSize.setText(""+bs.getGopSize());
        this.jTextFieldMtu.setText(""+bs.getMtu());
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSetActionPerformed
        bs.setVideoBitrate(Integer.parseInt(this.jTextFieldVideoBitrate.getText()));
        bs.setVideoScale(Float.parseFloat(this.jTextFieldVideoScale.getText()));
        bs.setAudioBirate(Integer.parseInt(this.jTextFieldAudioBitrate.getText()));
        bs.setGopSize(Integer.parseInt(this.jTextFieldGopSize.getText()));
        bs.setMtu(Integer.parseInt(this.jTextFieldMtu.getText()));
    }//GEN-LAST:event_jButtonSetActionPerformed

    private void jCheckBoxSmartSplitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSmartSplitterActionPerformed
        boolean selected = this.jCheckBoxSmartSplitter.getModel().isSelected();
        //try{
            if(selected){
                try{
                    bs.enableSmartSplitter();
                }
                catch(Exception e){
                    e.printStackTrace();
                    System.out.println("BroadcastServiceJFrame.jCheckBoxSmartSplitterActionPerformed "+e.getMessage());
                }
            } else{
                bs.disableSmartSplitter();
            }
        /*}
        catch(Exception e){
            e.printStackTrace();
        }*/
}//GEN-LAST:event_jCheckBoxSmartSplitterActionPerformed

    private void jButtonConfigProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigProgramActionPerformed
        int index = jComboBoxActiveProgramList.getSelectedIndex();
        if(index!=-1){
            String programName = (String)jComboBoxActiveProgramList.getItemAt(index);
            bs.showProgramConfig(programName);
        }
}//GEN-LAST:event_jButtonConfigProgramActionPerformed

    private void jRadioButtonTranscodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoTranscodeActionPerformed
        //System.out.println("jRadioButtonTranscodeActionPerformed "+evt.getActionCommand());
    	if(jRadioButtonH264.isSelected())
    		bs.setVideoTranscoder(this.jRadioButtonH264.getText());
    	else if(jRadioButtonMp2v.isSelected())
    		bs.setVideoTranscoder(jRadioButtonMp2v.getText());
    	else if(jRadioButtonNoTranscode.isSelected())
    		bs.setVideoTranscoder(jRadioButtonNoTranscode.getText());
    	else if(rdbtnAndr.isSelected())
    		bs.setVideoTranscoder(rdbtnAndr.getText());
    	else System.out.println("BroadcastServiceJFrame.jRadioButtonTranscodeActionPerformed error");
    }//GEN-LAST:event_jRadioButtonNoTranscodeActionPerformed

    /*private void jRadioButtonProtocolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoTranscodeActionPerformed
        if(rdbtnUdp.isSelected())
    		bs.setProtocol(E2EComm.UDP);
    	else if(rdbtnTcp.isSelected())
    		bs.setProtocol(E2EComm.TCP);
    }*/

    private void jCheckBoxRawBytesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxRawBytesActionPerformed
        boolean selected = this.jCheckBoxRawBytes.getModel().isSelected();
        if(selected){
            bs.setRawBytes(true);
        } else{
            bs.setRawBytes(false);
        }
    }//GEN-LAST:event_jCheckBoxRawBytesActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTranscode;
    private javax.swing.JButton jButtonActivateDvbT;
    private javax.swing.JButton jButtonActivateHttp;
    private javax.swing.JButton jButtonActivateProgram;
    private javax.swing.JButton jButtonChangeDirectory;
    private javax.swing.JButton jButtonChangeVlcDirectory;
    private javax.swing.JButton jButtonChangeWebcam;
    private javax.swing.JButton jButtonConfigProgram;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonRefreshProgramList;
    private javax.swing.JButton jButtonRefreshSourceList;
    private javax.swing.JButton jButtonSet;
    private javax.swing.JButton jButtonStopProgram;
    private javax.swing.JCheckBox jCheckBoxBroadcastSplitter;
    private javax.swing.JCheckBox jCheckBoxRawBytes;
    private javax.swing.JCheckBox jCheckBoxSmartSplitter;
    private javax.swing.JComboBox jComboBoxActiveProgramList;
    private javax.swing.JComboBox jComboBoxSourceList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonH264;
    private javax.swing.JRadioButton jRadioButtonMp2v;
    private javax.swing.JRadioButton jRadioButtonNoTranscode;
    //private javax.swing.JRadioButton rdbtnUdp;
    //private javax.swing.JRadioButton rdbtnTcp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaActiveProgramList;
    private javax.swing.JTextArea jTextAreaSourceList;
    private javax.swing.JTextField jTextFieldAudioBitrate;
    private javax.swing.JTextField jTextFieldCurrentDirectory;
    private javax.swing.JTextField jTextFieldFrequency;
    private javax.swing.JTextField jTextFieldGopSize;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldMtu;
    private javax.swing.JTextField jTextFieldNewDirectory;
    private javax.swing.JTextField jTextFieldProgram;
    private javax.swing.JTextField jTextFieldVideoBitrate;
    private javax.swing.JTextField jTextFieldVideoScale;
    private javax.swing.JTextField jTextFieldVlcDirectory;
    private javax.swing.JTextField jTextFieldWebcamName;
    private JRadioButton rdbtnAndr;
}
