/*
 * CommunicationSupportJFrame.java
 *
 * Created on 27 aprile 2010, 15.56
 */

package it.unibo.deis.lia.ramp.service.application;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * 
 */
public class ChatCommunicationSupportJFrame extends javax.swing.JFrame implements ChatCommunicationSupportInterface{
    
    private static final long serialVersionUID = 1L;
	
	private ChatCommunicationSupportOld cs;
    //private String[] contacts;
    /** Creates new form CommunicationSupportJFrame */
    public ChatCommunicationSupportJFrame(ChatCommunicationSupportOld cs,String[] contacts) {
        this.cs=cs;
        //this.contacts=contacts;
        initComponents();
        DefaultComboBoxModel dcm = new DefaultComboBoxModel(contacts);
        jComboBoxContacts.setModel(dcm);
        new RefreshMessages(this).start();
        setVisible(true);
        
    }
    
    private void getReceivedMessages() {
        String res="";
        Vector<String> messageList=cs.getReceivedMessages();
        for(String mess : messageList){
            
        	String[] splitmess= mess.split(": ");
        	
        	res+=i2s(Integer.valueOf(splitmess[0]))+": "+splitmess[1]+"\n";
        } 
        this.jTextAreaReceiveMessage.setText(res);
    }

    public void stopInteface(){
        setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButtonSend = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaWriteMessage = new javax.swing.JTextArea();
        jComboBoxContacts = new javax.swing.JComboBox();
        jButtonInvite = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReceiveMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CommunicationSupport");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonSend.setText("Send Message");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jTextAreaWriteMessage.setColumns(20);
        jTextAreaWriteMessage.setRows(5);
        jScrollPane2.setViewportView(jTextAreaWriteMessage);

        jComboBoxContacts.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonInvite.setText("Invite");
        jButtonInvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInviteActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Received Messages"));
        jTextAreaReceiveMessage.setColumns(20);
        jTextAreaReceiveMessage.setEditable(false);
        jTextAreaReceiveMessage.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReceiveMessage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBoxContacts, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jButtonInvite, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jButtonSend)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSend)
                    .addComponent(jComboBoxContacts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInvite))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInviteActionPerformed
        String contact=jComboBoxContacts.getSelectedItem().toString();
        try {
            cs.InviteContact(contact.hashCode());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonInviteActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        String msg=jTextAreaWriteMessage.getText();
        cs.SendMessage(msg);
        jTextAreaWriteMessage.setText("");
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("CommunicationSupporteJFrame: formWindowClosing");
        cs.stopService(false);
    }//GEN-LAST:event_formWindowClosing
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInvite;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JComboBox jComboBoxContacts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaReceiveMessage;
    private javax.swing.JTextArea jTextAreaWriteMessage;
    // End of variables declaration//GEN-END:variables
    
    private class RefreshMessages extends Thread{
    private ChatCommunicationSupportJFrame csjf;
    private RefreshMessages(ChatCommunicationSupportJFrame csjf){
        this.csjf=csjf;
    }
    @Override
    public void run(){
    	try{
            sleep(1000);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    	while(true){
            csjf.getReceivedMessages();
            try{
                sleep(1000);
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
        
    }
}
    
    private String i2s(int ipI){
    	//System.out.println("UnicastHeader.i2s: ipI="+ipI);
    	String ipS = "";
    	ipS += ( ( ipI >> 24 ) & 0xFF );
    	//System.out.println("UnicastHeader.i2s: ipS="+ipS);
    	ipS += ".";
    	ipS += ( ( ipI >> 16 ) & 0xFF );
    	//System.out.println("UnicastHeader.i2s: ipS="+ipS);
    	ipS += ".";
    	ipS += ( ( ipI >> 8 ) & 0xFF );
    	//System.out.println("UnicastHeader.i2s: ipS="+ipS); 
    	ipS += ".";
    	ipS += ( ( ipI >> 0 ) & 0xFF );
    	//System.out.println("UnicastHeader.i2s: ipS="+ipS);
    	return ipS;
    }
     
}
